### ISSUE TITLE
Allow DNS address lookup in Direct Connect

### ISSUE THREAD

**Issue by 7DataBits** [StunlockStudios/vrising-dedicated-server-instructions#77] opened 2022-05-26 10:42 UTC
Seems when using the Direct Connect feature only IP addresses are valid inputs but i would like to use my DNS entries to not always have to type numbers.

**Comment by khct** [comment] 2022-05-26 12:04
Duplicate of #4

**Closed by khct** 2022-05-26 12:04 UTC
