### ISSUE TITLE
Run server in linux

### ISSUE THREAD

**Issue by Cherrysaber** [StunlockStudios/vrising-dedicated-server-instructions#47] opened 2022-05-23 12:37 UTC
Linux Support Please!!!

**Comment by ich777** [comment] 2022-05-23 13:27
Duplicate of #1 

Currently possible through WINE.

I've created a Docker container see [here](https://github.com/ich777/docker-steamcmd-server/tree/vrising) on GitHub or [here](https://hub.docker.com/layers/steamcmd/ich777/steamcmd/vrising/images/sha256-c9dafa02191de81c1721b4e353172be79339fffab90b4261b34eb12fafdd69e2?context=explore) on DockerHub.

**Comment by nehart** [comment] 2022-05-24 05:48
A Linux version of the Server would be highly appreciated

**Comment by ich777** [comment] 2022-05-24 07:23
@nehart see #1 where the developers actually answered why there isn‘t a native Linux dedicated server yet.

**Closed** 2022-05-28 08:26 UTC
